export const TYPE = {
  // Maps
  GET_MAPS: "GET_MAPS",
  GET_MAPS_SUCCES: "GET_MAPS_SUCCES",
  GET_MAPS_FAIL: "GET_MAPS_FAIL",

  // Geolocation
  GET_GEOLOCATION: "GET_GEOLOCATION",
  GET_GEOLOCATION_SUCCES: "GET_GEOLOCATION_SUCCES",
  GET_GEOLOCATION_FAIL: "GET_GEOLOCATION_FAIL",

  // Gps
  GET_GPS: "GET_GPS",
  GET_GPS_SUCCES: "GET_GPS_SUCCES",
  GET_GPS_FAIL: "GET_GPS_FAIL",

  // khoang cach
  GET_KM: "GET_KM",
  GET_KM_SUCCES: "GET_KM_SUCCES",
  GET_KM_FAIL: "GET_KM_FAIL",

  // zoom and center
  SET_ZOOM_CENTER: "SET_ZOOM_CENTER",
  SET_ZOOM_CENTER_SUCCES: "SET_ZOOM_CENTER_SUCCES",
  SET_ZOOM_CENTER_FAIL: "SET_ZOOM_CENTER_FAIL",

  SET_UPDATE: "SET_UPDATE",

};
